package com.example.fieldsafesolar.data.util

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.fieldsafesolar.data.db.entity.EvidenceEntity
import com.example.fieldsafesolar.data.model.SafetyReport
import java.io.File
import java.time.ZoneId
import java.time.format.DateTimeFormatter

object SafetyReportPdfGenerator {

    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private const val MARGIN = 48f
    private const val CONTENT_W = PAGE_W - MARGIN * 2

    fun generate(report: SafetyReport, evidences: List<EvidenceEntity>, context: Context): File {
        val doc = PdfDocument()
        val writer = PageWriter(doc)

        writer.title("FieldSafe Solar")
        writer.title("Safety Inspection Report")
        writer.spacer(10f)
        writer.field("Date", formatDate(report))
        writer.field("Inspection", report.inspectionType.name.replace('_', ' '))
        writer.field("Report ID", report.reportId.take(36))
        writer.spacer(18f)
        writer.verdictBanner(report.overallDecision, report.severity)
        writer.spacer(8f)
        report.correctiveActionLabel?.let { label ->
            writer.correctiveActionBanner(label, report.overallDecision)
            writer.spacer(8f)
        }
        if (report.jhaConfirmed) {
            writer.field("Pre-Task JHA", "Confirmed — OSHA 29 CFR 1926.20(b)(2) / ANSI/SEIA 301-2025")
        } else {
            writer.field("Pre-Task JHA", "NOT CONFIRMED before this inspection")
        }
        writer.spacer(12f)
        writer.section("Summary", listOf(report.summary))
        writer.section("Observed Conditions", report.observedConditions)
        writer.section("Worker Confirmations", report.workerConfirmations)
        writer.section("Unverified Items", report.unverifiedItems)
        writer.section("Recommended Actions", report.recommendedActions)
        writer.section("Applicable Standards", report.applicableStandards)
        writer.section("Limitations", report.limitations)
        if (report.eewpPermitLines.isNotEmpty()) {
            writer.section("Energized Electrical Work Permit (NFPA 70E §130.2)", report.eewpPermitLines)
        }

        if (evidences.isNotEmpty()) {
            writer.sectionHeader("Photo Evidence")
            evidences.forEach { ev ->
                writer.spacer(8f)
                writer.body("• ${ev.caption}")
                writer.spacer(6f)
                loadCompressedBitmap(ev.fileUri)?.let { bmp ->
                    writer.drawImage(bmp)
                    bmp.recycle()
                }
            }
        }

        writer.spacer(24f)
        writer.footer("Generated by FieldSafe Solar  •  ${formatDate(report)}")
        writer.finish()

        val file = File(context.cacheDir, "report_${report.reportId.take(8)}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun formatDate(report: SafetyReport): String {
        val formatter = DateTimeFormatter.ofPattern("MMM dd, yyyy HH:mm")
            .withZone(ZoneId.systemDefault())
        return formatter.format(report.createdAt)
    }

    private fun loadCompressedBitmap(filePath: String, maxWidth: Int = 480): Bitmap? {
        return try {
            val opts = BitmapFactory.Options().apply { inJustDecodeBounds = true }
            BitmapFactory.decodeFile(filePath, opts)
            if (opts.outWidth <= 0) return null
            val scale = maxOf(opts.outWidth / maxWidth, 1)
            BitmapFactory.decodeFile(filePath, BitmapFactory.Options().apply { inSampleSize = scale })
        } catch (_: Exception) { null }
    }

    // ── PageWriter ──────────────────────────────────────────────────────────

    private class PageWriter(private val doc: PdfDocument) {
        private var page: PdfDocument.Page? = null
        private var canvas: Canvas? = null
        private var y = MARGIN
        private var pageNum = 0

        init { newPage() }

        private fun newPage() {
            page?.let { doc.finishPage(it) }
            pageNum++
            val info = PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create()
            val p = doc.startPage(info)
            page = p
            canvas = p.canvas
            y = MARGIN
        }

        private fun ensureSpace(needed: Float) {
            if (y + needed > PAGE_H - MARGIN) newPage()
        }

        fun finish() { page?.let { doc.finishPage(it) }; page = null; canvas = null }

        fun spacer(h: Float = 12f) { y += h }

        fun title(text: String) {
            ensureSpace(32f)
            val p = Paint().apply {
                textSize = 20f; typeface = Typeface.DEFAULT_BOLD; color = Color.BLACK; isAntiAlias = true
            }
            canvas!!.drawText(text, MARGIN, y + 20f, p)
            y += 28f
        }

        fun field(label: String, value: String) {
            ensureSpace(18f)
            val lp = Paint().apply { textSize = 10f; color = Color.GRAY; isAntiAlias = true }
            val vp = Paint().apply { textSize = 11f; color = Color.BLACK; isAntiAlias = true }
            canvas!!.drawText("$label: ", MARGIN, y + 11f, lp)
            canvas!!.drawText(value, MARGIN + lp.measureText("$label: "), y + 11f, vp)
            y += 16f
        }

        fun verdictBanner(decision: SafetyReport.Decision, severity: SafetyReport.Severity) {
            ensureSpace(56f)
            val bgColor = when (decision) {
                SafetyReport.Decision.PASS -> Color.rgb(0, 180, 70)
                SafetyReport.Decision.WARN -> Color.rgb(255, 145, 0)
                SafetyReport.Decision.FAIL, SafetyReport.Decision.STOP_WORK -> Color.rgb(200, 0, 0)
            }
            val rect = RectF(MARGIN, y, MARGIN + CONTENT_W, y + 48f)
            canvas!!.drawRoundRect(rect, 8f, 8f, Paint().apply { color = bgColor; style = Paint.Style.FILL })
            val tp = Paint().apply {
                textSize = 16f; typeface = Typeface.DEFAULT_BOLD; color = Color.WHITE; isAntiAlias = true
            }
            val label = "${decision.name.replace('_', ' ')}  •  Severity: ${severity.name}"
            canvas!!.drawText(label, MARGIN + 12f, y + 30f, tp)
            y += 56f
        }

        fun correctiveActionBanner(label: String, decision: SafetyReport.Decision) {
            ensureSpace(36f)
            val bgColor = when (decision) {
                SafetyReport.Decision.STOP_WORK -> Color.rgb(180, 0, 0)
                SafetyReport.Decision.FAIL -> Color.rgb(200, 80, 0)
                SafetyReport.Decision.WARN -> Color.rgb(140, 100, 0)
                SafetyReport.Decision.PASS -> Color.DKGRAY
            }
            val rect = RectF(MARGIN, y, MARGIN + CONTENT_W, y + 28f)
            canvas!!.drawRoundRect(rect, 4f, 4f, Paint().apply { color = bgColor; style = Paint.Style.FILL })
            val tp = Paint().apply { textSize = 9f; typeface = Typeface.DEFAULT_BOLD; color = Color.WHITE; isAntiAlias = true }
            canvas!!.drawText("CORRECTIVE ACTION REQUIRED: $label", MARGIN + 8f, y + 18f, tp)
            y += 32f
        }

        fun sectionHeader(title: String) {
            ensureSpace(24f)
            y += 8f
            val p = Paint().apply {
                textSize = 12f; typeface = Typeface.DEFAULT_BOLD; color = Color.DKGRAY; isAntiAlias = true
            }
            canvas!!.drawText(title.uppercase(), MARGIN, y + 12f, p)
            canvas!!.drawLine(MARGIN, y + 16f, MARGIN + CONTENT_W, y + 16f,
                Paint().apply { color = Color.LTGRAY; strokeWidth = 1f })
            y += 22f
        }

        fun body(text: String) {
            val p = Paint().apply { textSize = 10f; color = Color.DKGRAY; isAntiAlias = true }
            val lines = wrapText(text, p, CONTENT_W)
            lines.forEach { line ->
                ensureSpace(15f)
                canvas!!.drawText(line, MARGIN, y + 10f, p)
                y += 14f
            }
        }

        fun footer(text: String) {
            ensureSpace(20f)
            val p = Paint().apply { textSize = 9f; color = Color.GRAY; isAntiAlias = true }
            canvas!!.drawText(text, MARGIN, y + 9f, p)
            y += 14f
        }

        fun section(title: String, items: List<String>) {
            if (items.isEmpty()) return
            sectionHeader(title)
            items.forEach { body("• $it") }
        }

        fun drawImage(bitmap: Bitmap) {
            val maxW = CONTENT_W
            val aspect = bitmap.height.toFloat() / bitmap.width
            val drawW = minOf(maxW, bitmap.width.toFloat())
            val drawH = drawW * aspect
            ensureSpace(drawH + 8f)
            canvas!!.drawBitmap(
                bitmap, null,
                RectF(MARGIN, y, MARGIN + drawW, y + drawH),
                Paint().apply { isFilterBitmap = true }
            )
            y += drawH + 8f
        }

        private fun wrapText(text: String, paint: Paint, maxWidth: Float): List<String> {
            val words = text.split(" ")
            val lines = mutableListOf<String>()
            var current = ""
            for (word in words) {
                val test = if (current.isEmpty()) word else "$current $word"
                if (paint.measureText(test) <= maxWidth) {
                    current = test
                } else {
                    if (current.isNotEmpty()) lines.add(current)
                    current = word
                }
            }
            if (current.isNotEmpty()) lines.add(current)
            return lines.ifEmpty { listOf("") }
        }
    }
}
